#!/bin/bash

# Secure Apache HTTP Server 2.2 based on CIS Benchmark v3.6.0
# Target: Ubuntu/Debian systems
# Date: March 23, 2025
# Author: Generated by Grok 3 (xAI)

# Exit on any error
set -e

# Define variables
APACHE_USER="www-data"  # Default Apache user on Ubuntu/Debian
APACHE_GROUP="www-data"
HTTPD_CONF="/etc/apache2/apache2.conf"
SECURITY_CONF="/etc/apache2/conf-enabled/security.conf"
APACHE_SERVICE="apache2"
DOC_ROOT="/var/www/html"
LOG_DIR="/var/log/apache2"

# Ensure script is run as root
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root. Use sudo."
    exit 1
fi

# Install Apache and prerequisites
install_apache() {
    echo "Installing Apache 2.2 and required packages..."
    apt-get update
    # Note: Apache 2.2 may not be available in modern Ubuntu/Debian repos; installing apache2 (2.4) as fallback
    apt-get install -y apache2 libapache2-mod-security2 apparmor libapache2-mod-apparmor ufw
    a2enmod ssl headers  # Enable required modules
    echo "Apache and dependencies installed."
}

# Configure firewall with UFW
configure_firewall() {
    echo "Configuring UFW firewall..."
    ufw allow 'Apache Full'  # Allow HTTP and HTTPS
    ufw enable
    ufw status
    echo "Firewall configured to allow Apache traffic."
}

# Backup configuration files
backup_configs() {
    echo "Backing up existing configuration files..."
    cp -p "${HTTPD_CONF}" "${HTTPD_CONF}.bak-$(date +%F-%T)"
    [ -f "${SECURITY_CONF}" ] && cp -p "${SECURITY_CONF}" "${SECURITY_CONF}.bak-$(date +%F-%T)"
}

# Function to append to configuration file if not already present
append_if_not_present() {
    local file="$1"
    local directive="$2"
    if ! grep -q "^${directive}" "${file}"; then
        echo "${directive}" >> "${file}"
    fi
}

# 1. Planning and Installation
secure_planning_installation() {
    echo "Securing planning and installation..."

    # 1.1 Pre-Installation Planning Checklist (Manual)
    echo "1.1: Review security policies, network infrastructure, OS hardening, and logging manually."

    # 1.2 Ensure Server is Not Multi-Use (Not Scored)
    echo "1.2: Disabling unnecessary services..."
    systemctl list-unit-files --state=enabled | grep -v apache2 | awk '{print $1}' | xargs -I {} systemctl disable {}

    # 1.3 Ensure Apache is Installed from Appropriate Binaries (Not Scored)
    echo "1.3: Using official Ubuntu/Debian repositories for installation."
}

# 2. Apache Modules
secure_modules() {
    echo "Securing Apache modules..."

    # 2.1 Necessary Authentication/Authorization Modules (Not Scored)
    echo "2.1: Enable only required auth modules manually based on needs."

    # 2.2 Ensure Log Config Module is Enabled (Scored)
    append_if_not_present "${HTTPD_CONF}" "LoadModule log_config_module /usr/lib/apache2/modules/mod_log_config.so"

    # 2.3 Disable WebDAV Modules (Scored)
    a2dismod dav dav_fs 2>/dev/null || true

    # 2.4 Disable Status Module (Scored)
    a2dismod status 2>/dev/null || true

    # 2.5 Disable Autoindex Module (Scored)
    a2dismod autoindex 2>/dev/null || true

    # 2.6 Disable Proxy Modules (Scored)
    a2dismod proxy proxy_balancer proxy_ftp proxy_http proxy_connect proxy_ajp 2>/dev/null || true

    # 2.7 Disable User Directories Module (Scored)
    a2dismod userdir 2>/dev/null || true

    # 2.8 Disable Info Module (Scored)
    a2dismod info 2>/dev/null || true

    # 2.9 Disable Basic and Digest Auth Modules (Scored)
    a2dismod auth_basic auth_digest 2>/dev/null || true
}

# 3. Privileges, Permissions, and Ownership
secure_privileges_permissions() {
    echo "Securing privileges, permissions, and ownership..."

    # Ensure text files exist
    for file in authorizedsudousers.txt authorizedusers.txt; do
        if [ ! -f "$file" ]; then
            echo "Error: $file not found in current directory. Please create it with space-separated usernames."
            exit 1
        fi
    done

    # 3.1 Run as Non-Root User (Scored)
    sed -i "s/^User .*/User ${APACHE_USER}/" "${HTTPD_CONF}"
    sed -i "s/^Group .*/Group ${APACHE_GROUP}/" "${HTTPD_CONF}"

    # 3.2 Invalid Shell for Apache User (Scored)
    chsh -s /usr/sbin/nologin "${APACHE_USER}"

    # 3.3 Lock Apache User Account (Scored)
    passwd -l "${APACHE_USER}"

    # Process sudo users from authorizedsudousers.txt
    echo "Adding authorized sudo users from authorizedsudousers.txt..."
    sudo_users=$(cat authorizedsudousers.txt | tr -s ' ' | tr ' ' '\n' | grep -v '^$')
    for user in $sudo_users; do
        if ! id "$user" >/dev/null 2>&1; then
            useradd -m -s /bin/bash "$user"
            echo "$user ALL=(ALL:ALL) ALL" > "/etc/sudoers.d/$user"
            chmod 440 "/etc/sudoers.d/$user"
            echo "Created sudo user: $user"
        else
            echo "Sudo user $user already exists, ensuring sudo privileges..."
            if ! groups "$user" | grep -q sudo; then
                usermod -aG sudo "$user"
            fi
        fi
    done

    # Process regular users from authorizedusers.txt
    echo "Adding authorized regular users from authorizedusers.txt..."
    regular_users=$(cat authorizedusers.txt | tr -s ' ' | tr ' ' '\n' | grep -v '^$')
    for user in $regular_users; do
        if ! id "$user" >/dev/null 2>&1; then
            useradd -m -s /bin/bash "$user"
            echo "Created regular user: $user"
        else
            echo "Regular user $user already exists, skipping creation."
        fi
    done

    # 3.4 Owned by Root (Scored)
    chown -R root:root /etc/apache2 /usr/lib/apache2

    # 3.5 Group Set Correctly (Scored)
    chgrp -R "${APACHE_GROUP}" "${DOC_ROOT}" "${LOG_DIR}"

    # 3.6 Restrict Other Write Access (Scored)
    chmod -R o-w /etc/apache2 /usr/lib/apache2 "${DOC_ROOT}" "${LOG_DIR}"

    # 3.7 Secure Core Dump Directory (Scored)
    append_if_not_present "${HTTPD_CONF}" "CoreDumpDirectory ${LOG_DIR}"
    chmod 750 "${LOG_DIR}"
    chown root:"${APACHE_GROUP}" "${LOG_DIR}"

    # 3.8 Secure Lock File (Scored)
    chmod 640 "${LOG_DIR}/accept.lock" 2>/dev/null || true
    chown root:"${APACHE_GROUP}" "${LOG_DIR}/accept.lock" 2>/dev/null || true

    # 3.9 Secure Pid File (Scored)
    append_if_not_present "${HTTPD_CONF}" "PidFile ${LOG_DIR}/apache2.pid"
    chmod 644 "${LOG_DIR}/apache2.pid" 2>/dev/null || true
    chown root:"${APACHE_GROUP}" "${LOG_DIR}/apache2.pid" 2>/dev/null || true

    # 3.10 Secure ScoreBoard File (Scored)
    chmod 644 "${LOG_DIR}/apache_status" 2>/dev/null || true
    chown root:"${APACHE_GROUP}" "${LOG_DIR}/apache_status" 2>/dev/null || true

    # 3.11 Restrict Group Write Access (Scored)
    chmod -R g-w /etc/apache2 /usr/lib/apache2

    # 3.12 Restrict Document Root Group Write (Scored)
    chmod -R g-w "${DOC_ROOT}"

    # 3.13 Special Purpose Writable Directories (Not Scored)
    echo "3.13: Configure writable directories manually as needed."
}

# 4. Apache Access Control
secure_access_control() {
    echo "Securing Apache access control..."

    # Ensure security.conf exists
    [ ! -f "${SECURITY_CONF}" ] && touch "${SECURITY_CONF}"

    # 4.1 Deny Access to OS Root (Scored)
    cat <<EOF > "${SECURITY_CONF}"
<Directory />
    Order Deny,Allow
    Deny from all
    Options None
    AllowOverride None
</Directory>
EOF
    append_if_not_present "${HTTPD_CONF}" "Include conf-enabled/security.conf"

    # 4.2 Appropriate Web Content Access (Not Scored)
    echo "4.2: Configure web content access in <Directory> blocks manually."

    # 4.3 Disable Override for OS Root (Scored)
    # Already set in 4.1

    # 4.4 Disable Override for All Directories (Scored)
    append_if_not_present "${SECURITY_CONF}" "<Directory ${DOC_ROOT}>\n    AllowOverride None\n</Directory>"
}

# 5. Features, Content, and Options
secure_features_content() {
    echo "Securing features, content, and options..."

    # 5.1 Restrict OS Root Options (Scored)
    # Already set in 4.1

    # 5.2 Restrict Web Root Options (Scored)
    append_if_not_present "${SECURITY_CONF}" "<Directory ${DOC_ROOT}>\n    Options -Indexes -FollowSymLinks -ExecCGI -Includes\n</Directory>"

    # 5.3 Minimize Other Directory Options (Scored)
    echo "5.3: Minimize options for other directories manually."

    # 5.4 Remove Default HTML Content (Scored)
    rm -f "${DOC_ROOT}/index.html" 2>/dev/null || true

    # 5.5 Remove printenv CGI Script (Scored)
    rm -f "/usr/lib/cgi-bin/printenv" 2>/dev/null || true

    # 5.6 Remove test-cgi Script (Scored)
    rm -f "/usr/lib/cgi-bin/test-cgi" 2>/dev/null || true

    # 5.7 Restrict HTTP Methods (Scored)
    append_if_not_present "${SECURITY_CONF}" "<LimitExcept GET POST HEAD>\n    Deny from all\n</LimitExcept>"

    # 5.8 Disable TRACE Method (Scored)
    append_if_not_present "${HTTPD_CONF}" "TraceEnable off"

    # 5.9 Disallow Old HTTP Protocols (Scored)
    append_if_not_present "${HTTPD_CONF}" "Protocols h2 http/1.1"

    # 5.10 Restrict .ht* Files (Scored)
    append_if_not_present "${SECURITY_CONF}" "<FilesMatch \"^\.ht\">\n    Order Deny,Allow\n    Deny from all\n</FilesMatch>"

    # 5.11 Restrict Inappropriate Extensions (Scored)
    append_if_not_present "${SECURITY_CONF}" "<FilesMatch \"\.(bak|conf|cfg|ini|log|sh|sql)$\">\n    Order Deny,Allow\n    Deny from all\n</FilesMatch>"

    # 5.12 Disallow IP-Based Requests (Scored)
    append_if_not_present "${HTTPD_CONF}" "ServerName localhost"

    # 5.13 Specify Listening IP (Scored)
    sed -i "s/^Listen .*/Listen 127.0.0.1:80/" "${HTTPD_CONF}"  # Adjust IP/port as needed

    # 5.14 Restrict Browser Framing (Scored)
    append_if_not_present "${HTTPD_CONF}" "Header always append X-Frame-Options SAMEORIGIN"
}

# 6. Operations - Logging, Monitoring, and Maintenance
secure_operations() {
    echo "Securing operations, logging, and maintenance..."

    # 6.1 Configure Error Log (Scored)
    append_if_not_present "${HTTPD_CONF}" "ErrorLog ${LOG_DIR}/error.log"
    append_if_not_present "${HTTPD_CONF}" "LogLevel warn"

    # 6.2 Syslog Facility for Error Logging (Scored)
    append_if_not_present "${HTTPD_CONF}" "ErrorLog syslog:local1"

    # 6.3 Configure Access Log (Scored)
    append_if_not_present "${HTTPD_CONF}" "CustomLog ${LOG_DIR}/access.log combined"

    # 6.4 Log Storage and Rotation (Scored)
    echo "6.4: Log rotation is handled by Ubuntu/Debian's default logrotate config."

    # 6.5 Apply Patches (Scored)
    apt-get upgrade -y apache2

    # 6.6 Install and Enable ModSecurity (Scored)
    a2enmod security2

    # 6.7 Install OWASP ModSecurity CRS (Scored)
    apt-get install -y modsecurity-crs
    echo "6.7: OWASP CRS installed. Configure rules in /etc/modsecurity/ manually if needed."
}

# 7. SSL/TLS
secure_ssl_tls() {
    echo "Securing SSL/TLS..."

    # 7.1 Install mod_ssl (Scored)
    a2enmod ssl

    # 7.2-7.3 Valid Certificate and Private Key Protection (Scored)
    echo "7.2-7.3: Install a valid SSL certificate and secure private key manually (e.g., /etc/ssl/)."

    # 7.4-7.8 Disable Weak Protocols and Ciphers (Scored)
    cat <<EOF >> "${SECURITY_CONF}"
SSLEnabled on
SSLProtocol -all +TLSv1.2 +TLSv1.3
SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
SSLHonorCipherOrder on
SSLCompression off
SSLRenegotiation off
EOF

    # 7.9 All Content via HTTPS (Scored)
    append_if_not_present "${SECURITY_CONF}" "<VirtualHost *:80>\n    Redirect permanent / https://localhost/\n</VirtualHost>"

    # 7.10 Disable TLSv1.0 and TLSv1.1 (Scored)
    # Already handled in 7.4

    # 7.11 Enable HSTS (Scored)
    append_if_not_present "${HTTPD_CONF}" "Header always set Strict-Transport-Security \"max-age=31536000; includeSubDomains\""

    # 7.12 Forward Secrecy Ciphers (Scored)
    # Already handled in 7.5
}

# 8. Information Leakage
secure_info_leakage() {
    echo "Securing against information leakage..."

    # 8.1 ServerTokens (Scored)
    append_if_not_present "${HTTPD_CONF}" "ServerTokens Prod"

    # 8.2 ServerSignature (Scored)
    append_if_not_present "${HTTPD_CONF}" "ServerSignature Off"

    # 8.3 Remove Default Content (Scored)
    rm -rf "/usr/share/apache2/manual" 2>/dev/null || true

    # 8.4 ETag Inodes (Scored)
    append_if_not_present "${HTTPD_CONF}" "FileETag None"
}

# 9. Denial of Service Mitigations
secure_dos_mitigations() {
    echo "Securing against DoS..."

    # 9.1-9.6 Configure Timeouts and KeepAlive (Scored)
    cat <<EOF >> "${HTTPD_CONF}"
TimeOut 10
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5
RequestReadTimeout header=20-40,MinRate=500 body=20,MinRate=500
EOF
}

# 10. Request Limits
secure_request_limits() {
    echo "Securing request limits..."

    # 10.1-10.4 Set Request Limits (Scored)
    cat <<EOF >> "${HTTPD_CONF}"
LimitRequestLine 512
LimitRequestFields 100
LimitRequestFieldSize 1024
LimitRequestBody 102400
EOF
}

# 12. Enable AppArmor
secure_apparmor() {
    echo "Securing with AppArmor..."

    # 12.1 Enable AppArmor (Scored)
    systemctl enable apparmor
    systemctl start apparmor

    # 12.2 Configure Profile (Not Scored)
    aa-autodep apache2
    aa-complain /usr/sbin/apache2
    service "${APACHE_SERVICE}" restart
    echo "12.2: Test application, then run 'aa-logprof' to update profile manually."

    # 12.3 Enforce Mode (Scored)
    aa-enforce /usr/sbin/apache2
    service "${APACHE_SERVICE}" restart
    aa-status
}

# Main execution
main() {
    echo "Securing Apache HTTP Server 2.2 per CIS Benchmark v3.6.0 on Ubuntu/Debian..."
    install_apache
    configure_firewall
    backup_configs
    secure_planning_installation
    secure_modules
    secure_privileges_permissions
    secure_access_control
    secure_features_content
    secure_operations
    secure_ssl_tls
    secure_info_leakage
    secure_dos_mitigations
    secure_request_limits
    secure_apparmor

    # Restart Apache to apply changes
    echo "Restarting Apache service..."
    service "${APACHE_SERVICE}" restart

    echo "Apache security hardening complete. Review manual steps and test thoroughly."
}

main
